# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy well-demo

on:
  push:
    branches:
      - main
    paths:
      - react-well-demo/**
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'

      - name: set up npmrc
        run: |
          cd ./react-well-demo
          echo "react-well-demo/.npmrc" > .npmrc
          echo "@equinor:registry=https://npm.pkg.github.com/equinor" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> .npmrc
          cat .npmrc

      - name: npm install, build, and test
        run: |
          cd ./react-well-demo
          npm install
          
      - name: install wellx
        run: |
          cd ./react-well-demo
          npm set registry https://registry.npmjs.org/
          npm i
          npm install @equinor/wellx-wellog --registry https://npm.pkg.github.com/equinor
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'well-demo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISHPROFILE_WELL_DEMO }}
          package: .
